# Generated by Django 6.0.4 on 2026-04-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Коли нагадати?'),
        ),
    ]
